version: '3.7'
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mail
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

